import { collection, doc, setDoc, serverTimestamp } from 'firebase/firestore'
import { db } from './config'

const NOVELS = [
  {
    id: 'btth',
    title: 'Battle Through the Heavens',
    author: 'Heavenly Silkworm Potato',
    description: 'In a land where no magic is present, a young boy Xiao Yan, who had shown talents none had seen in decades, suddenly lost everything three years ago — his powers, his reputation, and his promise to his mother. What mystical possession was he left with by his mother? With overwhelming difficulties surrounding him, and the loss of the past, will he rise to challenge the heavens?',
    coverUrl: 'https://i.imgur.com/3Y7JPEW.jpg',
    status: 'completed',
    genres: ['Xianxia', 'Action', 'Adventure', 'Romance'],
    tags: ['Cultivation', 'Weak-to-Strong', 'Alchemy', 'Tournament'],
    sourceUrl: 'https://www.wuxiaworld.com/novel/battle-through-the-heavens',
    totalChapters: 1648,
    year: 2009,
    avgRating: 8.1,
    ratingCount: 4820,
    ratingSum: 39042,
    reviewCount: 312,
  },
  {
    id: 'issth',
    title: 'I Shall Seal the Heavens',
    author: 'Er Gen',
    description: 'What I want, the Heavens shall not lack! What I don\'t want, had better not exist in the Heavens! This is a story which originates between the Eighth and Ninth Mountains, the world in which the strong prey upon the weak. "My Name is Meng Hao! The Ninth Generation Demon Sealer, I shall seal the Heavens!"',
    coverUrl: 'https://i.imgur.com/KkJbJz0.jpg',
    status: 'completed',
    genres: ['Xianxia', 'Action', 'Drama'],
    tags: ['Cultivation', 'Immortal', 'Weak-to-Strong', 'Sect'],
    sourceUrl: 'https://www.wuxiaworld.com/novel/i-shall-seal-the-heavens',
    totalChapters: 1614,
    year: 2014,
    avgRating: 9.0,
    ratingCount: 6103,
    ratingSum: 54927,
    reviewCount: 501,
  },
  {
    id: 'lotm',
    title: 'Lord of the Mysteries',
    author: 'Cuttlefish That Loves Diving',
    description: 'In the fog of history and darkness, beyond the boundary of light and shadows, someone will give you hints but they are not gods. This is a story of Victorian era mysteries. Klein Moretti is enveloped by a mysterious fog of darkness and starts over as a detective.',
    coverUrl: 'https://i.imgur.com/9T3xpE0.jpg',
    status: 'completed',
    genres: ['Mystery', 'Fantasy', 'Horror', 'Steampunk'],
    tags: ['Victorian', 'Secret Society', 'Tarot', 'Eldritch', 'Transmigration'],
    sourceUrl: 'https://www.webnovel.com/book/lord-of-the-mysteries_11008289906245805',
    totalChapters: 1432,
    year: 2018,
    avgRating: 9.6,
    ratingCount: 9841,
    ratingSum: 94473,
    reviewCount: 1204,
  },
  {
    id: 'solo-leveling',
    title: 'Solo Leveling',
    author: 'Chu-Gong',
    description: '10 years ago, after "the Gate" that connects the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as "Hunters". However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. I\'m someone who has to risk his life in the lowliest of dungeons, the "World\'s Weakest".',
    coverUrl: 'https://i.imgur.com/qGlYF7a.jpg',
    status: 'completed',
    genres: ['Action', 'Fantasy', 'System'],
    tags: ['Dungeons', 'Leveling', 'OP MC', 'Gate', 'Hunter'],
    sourceUrl: 'https://www.novelupdates.com/series/only-i-level-up/',
    totalChapters: 270,
    year: 2016,
    avgRating: 9.2,
    ratingCount: 12503,
    ratingSum: 115027,
    reviewCount: 2013,
  },
  {
    id: 'omniscient-reader',
    title: 'Omniscient Reader\'s Viewpoint',
    author: 'Sing-Shong',
    description: 'Only I know the end of this world. One day our MC finds himself in the world of the novel he had been reading. But, the story had been long completed. So what now?',
    coverUrl: 'https://i.imgur.com/wLM8tSl.jpg',
    status: 'completed',
    genres: ['Action', 'Fantasy', 'Drama', 'Apocalypse'],
    tags: ['Meta', 'System', 'Regression', 'Scenarios', 'Korean'],
    sourceUrl: 'https://www.novelupdates.com/series/omniscient-readers-viewpoint/',
    totalChapters: 551,
    year: 2019,
    avgRating: 9.4,
    ratingCount: 8921,
    ratingSum: 83856,
    reviewCount: 1450,
  },
  {
    id: 'reverend-insanity',
    title: 'Reverend Insanity',
    author: 'Gu Zhen Ren',
    description: 'Humans are clever in tens of thousands of ways, Gu are the true creation of heaven and earth. Glory and wealth are merely shallow utensils, my desire is the dao of eternal life. Spring and Autumn, vicissitudes of life, youth left as time flies... a thousand years of life is but a moment in the long river of time.',
    coverUrl: 'https://i.imgur.com/VqGPjdN.jpg',
    status: 'completed',
    genres: ['Xianxia', 'Action', 'Horror', 'Philosophical'],
    tags: ['Villain Protagonist', 'Dark', 'Anti-Hero', 'Reincarnation', 'Gu Worms'],
    sourceUrl: 'https://www.novelupdates.com/series/reverend-insanity/',
    totalChapters: 2334,
    year: 2012,
    avgRating: 9.3,
    ratingCount: 7654,
    ratingSum: 71182,
    reviewCount: 987,
  },
  {
    id: 'rmji',
    title: 'Renegade Immortal',
    author: 'Er Gen',
    description: 'Wang Lin is a very smart boy with loving parents. Although his parents are not too wealthy, they still give him a happy life. Wang Lin meets a talented teen and with the help of a senior in the family, he is allowed to enter a sect of Xianxia. His life is forever changed.',
    coverUrl: 'https://i.imgur.com/X8vO8MD.jpg',
    status: 'completed',
    genres: ['Xianxia', 'Action', 'Drama'],
    tags: ['Cultivation', 'Immortal', 'Reincarnation', 'Dark'],
    sourceUrl: 'https://www.wuxiaworld.com/novel/renegade-immortal',
    totalChapters: 2107,
    year: 2009,
    avgRating: 8.8,
    ratingCount: 3201,
    ratingSum: 28168,
    reviewCount: 411,
  },
  {
    id: 'wandering-inn',
    title: 'The Wandering Inn',
    author: 'pirateaba',
    description: 'An inn is a place to rest, to share a story or a drink. To celebrate in good times, or to find comfort in bad. But it is also a place of mystery. Of secrets. And of danger. This is the story of Erin Solstice, a young woman who finds herself in another world.',
    coverUrl: 'https://i.imgur.com/FTn2xZ1.jpg',
    status: 'ongoing',
    genres: ['Isekai', 'Slice of Life', 'Fantasy', 'Adventure'],
    tags: ['Female Protagonist', 'Inn', 'Monsters', 'GameLit', 'Long'],
    sourceUrl: 'https://www.wanderinginn.com/',
    totalChapters: 400,
    year: 2016,
    avgRating: 9.0,
    ratingCount: 5432,
    ratingSum: 48888,
    reviewCount: 723,
  },
  {
    id: 'shadow-slave',
    title: 'Shadow Slave',
    author: 'Guiltythree',
    description: 'Growing up in poverty, Sunny never expected anything good from life. However, even he did not anticipate being chosen by the Nightmare Spell and becoming one of the Awakened - an elite group of people gifted with supernatural powers.',
    coverUrl: 'https://i.imgur.com/JLqLO9a.jpg',
    status: 'ongoing',
    genres: ['Action', 'Fantasy', 'Dark', 'System'],
    tags: ['Nightmare', 'Shadows', 'Weak-to-Strong', 'Survival', 'Unique Magic'],
    sourceUrl: 'https://www.webnovel.com/book/shadow-slave_18050586206931605',
    totalChapters: 1800,
    year: 2021,
    avgRating: 9.1,
    ratingCount: 11230,
    ratingSum: 102183,
    reviewCount: 1893,
  },
  {
    id: 'primal-hunter',
    title: 'The Primal Hunter',
    author: 'Zogarth',
    description: 'On just another average day, Jake wakes up to find that Earth has been integrated into a vast multiverse of worlds. Suddenly levels, stats, and skills are real, and the only way to progress is to hunt.',
    coverUrl: 'https://i.imgur.com/bklJHJA.jpg',
    status: 'ongoing',
    genres: ['Action', 'Fantasy', 'System', 'LitRPG'],
    tags: ['Dungeons', 'Leveling', 'Archer', 'Integration', 'Crafting'],
    sourceUrl: 'https://www.royalroad.com/fiction/36049/the-primal-hunter',
    totalChapters: 1200,
    year: 2021,
    avgRating: 8.7,
    ratingCount: 6790,
    ratingSum: 59073,
    reviewCount: 892,
  },
  {
    id: 'beginning-after-end',
    title: 'The Beginning After The End',
    author: 'TurtleMe',
    description: 'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Reborn into a new world filled with magic and monsters, the king has a second chance to relive his life.',
    coverUrl: 'https://i.imgur.com/3Kpq4n1.jpg',
    status: 'completed',
    genres: ['Isekai', 'Fantasy', 'Action', 'Adventure'],
    tags: ['Reincarnation', 'Magic', 'School', 'Prodigy', 'OP MC'],
    sourceUrl: 'https://tapas.io/series/tbate',
    totalChapters: 550,
    year: 2018,
    avgRating: 8.4,
    ratingCount: 15200,
    ratingSum: 127680,
    reviewCount: 3201,
  },
  {
    id: 'mother-of-learning',
    title: 'Mother of Learning',
    author: 'nobody103',
    description: 'Zorian Kazinski is a young mage of humble birth and below-average skills, attending his third year of education at Cyoria\'s magical academy. He is a diligent student, but his efforts seem to lack the magic touch - the ability to translate hard work and study into success.',
    coverUrl: 'https://i.imgur.com/FzVlYTb.jpg',
    status: 'completed',
    genres: ['Fantasy', 'Mystery', 'Magic', 'Time Loop'],
    tags: ['Time Loop', 'Slow Progression', 'Academy', 'Mage', 'Western Fantasy'],
    sourceUrl: 'https://www.royalroad.com/fiction/21220/mother-of-learning',
    totalChapters: 93,
    year: 2011,
    avgRating: 9.5,
    ratingCount: 8905,
    ratingSum: 84597,
    reviewCount: 1102,
  },
  {
    id: 'all-things-wrong',
    title: 'All Things Wrong',
    author: 'Drunk for Poetry',
    description: 'Li Huowang just wants to go home. But the world he finds himself in is one where the boundary between sanity and madness is paper thin, and the horrors lurking beneath the surface of his rural Chinese environment are beyond imagination.',
    coverUrl: 'https://i.imgur.com/2bNhFhm.jpg',
    status: 'completed',
    genres: ['Horror', 'Mystery', 'Dark Fantasy', 'Philosophical'],
    tags: ['Psychological', 'Unreliable Narrator', 'Chinese Mythology', 'Slow Burn'],
    sourceUrl: 'https://www.webnovel.com/book/all-things-wrong_23400316806754505',
    totalChapters: 318,
    year: 2020,
    avgRating: 8.9,
    ratingCount: 3450,
    ratingSum: 30705,
    reviewCount: 567,
  },
  {
    id: 'cradle',
    title: 'Cradle (Unsouled)',
    author: 'Will Wight',
    description: 'Sacred artists follow a simple rule: Strive to become the best Sacred artist you can. Young Wei Shi Lindon is Unsouled, a Sacred artist who has the lowest possible ranking.',
    coverUrl: 'https://i.imgur.com/pR2JkfH.jpg',
    status: 'completed',
    genres: ['Xianxia', 'Action', 'Fantasy'],
    tags: ['Cultivation', 'Progression Fantasy', 'Western', 'Tournament', 'Underdog'],
    sourceUrl: 'https://www.willwight.com/books/unsouled/',
    totalChapters: 3600,
    year: 2016,
    avgRating: 9.0,
    ratingCount: 9100,
    ratingSum: 81900,
    reviewCount: 1560,
  },
  {
    id: 'dungeon-crawler-carl',
    title: 'Dungeon Crawler Carl',
    author: 'Matt Dinniman',
    description: 'The apocalypse will be televised! A nuclear war? No. A zombie plague? No. An asteroid? Nope. The apocalypse turns out to be — an alien game show, where the contestants are humans on Earth.',
    coverUrl: 'https://i.imgur.com/ABrKhOn.jpg',
    status: 'ongoing',
    genres: ['LitRPG', 'Comedy', 'Action', 'Apocalypse'],
    tags: ['Dungeon', 'Cat', 'Humor', 'GameLit', 'Satire'],
    sourceUrl: 'https://www.royalroad.com/fiction/42188/dungeon-crawler-carl',
    totalChapters: 2100,
    year: 2020,
    avgRating: 9.3,
    ratingCount: 13400,
    ratingSum: 124620,
    reviewCount: 2780,
  },
]

export async function seedNovels() {
  const novelsCol = collection(db, 'novels')
  let count = 0

  for (const novel of NOVELS) {
    const { id, ...data } = novel
    await setDoc(doc(novelsCol, id), {
      ...data,
      addedAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    })
    count++
    console.log(`Seeded ${count}/${NOVELS.length}: ${novel.title}`)
  }

  console.log('Seeding complete!')
}
